extension ThemeRole {
    /// Every role, in `ThemeColors`' declaration order (`ThemeRoleTests` checks the two agree).
    public static let all: [ThemeRole] = [
        ThemeRole("backgroundTop", "Background top", .surfaces, \.backgroundTop),
        ThemeRole("backgroundBottom", "Background bottom", .surfaces, \.backgroundBottom),
        ThemeRole("glassFill", "Glass", .surfaces, \.glassFill, allowsOpacity: true),
        ThemeRole("glassStroke", "Glass hairline", .surfaces, \.glassStroke, allowsOpacity: true),
        ThemeRole("panelBase", "Panel base", .surfaces, \.panelBase),
        ThemeRole("nodeBody", "Node body", .surfaces, \.nodeBody),
        ThemeRole("field", "Fields and tracks", .surfaces, \.field),
        ThemeRole("foreground", "Text", .text, \.foreground),
        ThemeRole("comment", "Secondary text", .text, \.comment),
        ThemeRole("textOnAccent", "Text on accents", .text, \.textOnAccent),
        ThemeRole("accent", "Accent", .interaction, \.accent),
        ThemeRole("focus", "Focus and hover", .interaction, \.focus),
        ThemeRole("selection", "Selection", .interaction, \.selection),
        ThemeRole("valueHeader", "Value nodes", .nodes, \.valueHeader),
        ThemeRole("profileHeader", "Profile nodes", .nodes, \.profileHeader),
        ThemeRole("solidHeader", "Solid nodes", .nodes, \.solidHeader),
        ThemeRole("selectionHeader", "Selection rules", .nodes, \.selectionHeader),
        ThemeRole("featureHeader", "Feature nodes", .nodes, \.featureHeader),
        ThemeRole("outputHeader", "Output node", .nodes, \.outputHeader),
        ThemeRole("success", "Success", .status, \.success),
        ThemeRole("warning", "Warning", .status, \.warning),
        ThemeRole("error", "Error", .status, \.error),
        ThemeRole("shadeLight", "Shading, lit", .model, \.shadeLight),
        ThemeRole("shadeDark", "Shading, unlit", .model, \.shadeDark),
        ThemeRole("edge", "Edges", .model, \.edge, allowsOpacity: true),
        ThemeRole("gridMinor", "Grid, minor lines", .model, \.gridMinor),
        ThemeRole("gridMajor", "Grid, major lines", .model, \.gridMajor),
        ThemeRole("cubeFace", "View cube faces", .widgets, \.cubeFace),
        ThemeRole("cubeRim", "View cube rim", .widgets, \.cubeRim),
        ThemeRole("cubeLabel", "View cube labels", .widgets, \.cubeLabel),
        ThemeRole("axisX", "X axis", .widgets, \.axisX),
        ThemeRole("axisY", "Y axis", .widgets, \.axisY),
        ThemeRole("axisZ", "Z axis", .widgets, \.axisZ),
        ThemeRole("sketchUnderConstrained", "Under-constrained", .sketcher, \.sketchUnderConstrained),
        ThemeRole("sketchFullyConstrained", "Fully constrained", .sketcher, \.sketchFullyConstrained),
        ThemeRole("sketchConflicting", "Conflicting", .sketcher, \.sketchConflicting),
        ThemeRole("sketchConstruction", "Construction", .sketcher, \.sketchConstruction),
        ThemeRole("sketchProjected", "Projected", .sketcher, \.sketchProjected),
    ]
}
